services:
  - type: web
    name: ai-smarthire
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn AI_SmartHire.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
